### ISSUE TITLE
Jobs still run after context is done

### ISSUE THREAD

**Issue by BredSt** [oze4/workerpoolxt#10] opened 2020-10-20 15:20 UTC
HI,

I've some time to run some extended test (on the master branch code ) and I found one issue.:) 

in case you provide a `timeout` and `retry` to specific task you are getting the error that the time passed which is ok. However, the task is **proceed** and **continue to run** which is problematic as the timeout should win.
User should define a timeout **as limit** to the task and after the job exceed the timeout it should be **killed to free resources** as if it pass the results after the timeout the results is not valid anymore...
as the `jobResults := wp.StopWaitXT()` should handle it.
WDYT?

**Comment by oze4** [comment] 2020-10-20 17:03
Do you have some code I can test with?

Let's say you have a job that sleeps for 1 hour but your timeout is 1 second. How would you go about cancelling a job that is just sleeping (or in flight)?

**Comment by oze4** [comment] 2020-10-20 17:38
This code reproduces the issue, but again, I am not aware of any way possible to stop a function from running in the middle of it running.

```golang
func TestTimeoutRemovesJob(t *testing.T) {
	wp := makeDefaultWp()

	ctx, done := context.WithTimeout(context.Background(), time.Duration(time.Second))
	defer done()
	wp.SubmitXT(Job{
		Name: "a",
		Context: ctx,
		Task: func(o Options) Result {
			for i := 0; i < 10000; i++ {
				fmt.Println("a")
				time.Sleep(time.Millisecond*200)
			}
			return Result{Data: true}
		},
	})

	wp.SubmitXT(Job{
		Name: "b",
		Task: func(o Options) Result {
			time.Sleep(time.Duration(time.Second*10))
			return Result{Data: true}
		},
	})

	res := wp.StopWaitXT()
	fmt.Println(res)
}
```

**Comment by oze4** [comment] 2020-10-20 23:52
This one is really stumping me.... I reached out to the author of workerpool (https://github.com/gammazero/workerpool/issues/40) for help on this.. I think it is out of my understanding of Go as to why this is happening.

[You can view a better POC here](https://play.golang.org/p/pYGz7Ryj8VQ)

Any idea how to resolve this?

**Comment by BredSt** [comment] 2020-10-21 07:42
HI,

I saw that you got a nice answer which solve the problem :-) , when to expect to new version as we want to run it on prod.

Thanks!

**Comment by oze4** [comment] 2020-10-21 16:58
@BredSt what makes you think the problem is resovled?

**Comment by BredSt** [comment] 2020-10-22 06:19
Hi @oze4 - this replay https://github.com/oze4/workerpoolxt/issues/7#issuecomment-713332831 but I understand that it a bit tricky as the tread continue..., now I saw this https://github.com/gammazero/workerpool/issues/40#issuecomment-714178180
Do you think that we have a solution to this problem?

**Comment by oze4** [comment] 2020-12-11 05:44
[Closing per](https://github.com/oze4/workerpoolxt/issues/12#issuecomment-716794599)

**Closed by oze4** 2020-12-11 05:44 UTC
Labels: bug, help wanted
